apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: kube-monitoring
data:
  prometheus.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
          {
            "access":"proxy",
            "editable": true,
            "name": "prometheus",
            "orgId": 1,
            "type": "prometheus",
            "url": "http://prometheus.kube-monitoring.svc.cluster.local:9090",
            "version": 1
          }
      ]
    }
