apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: kube-monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '3000'
spec:
  selector:
    app: grafana  
  ports:
    - port: 8080
      targetPort: 3000
