route:
  receiver: mattermost
  group_by: ['alertname', 'priority']
  group_wait: 10s
  repeat_interval: 30m
  routes:
    - receiver: mattermost
      match:
        severity: mattermost
      group_wait: 10s
      repeat_interval: 1m

receivers:
- name: mattermost
  webhook_configs:
    - send_resolved: true
      url: http://<<mattermost_host>>:<<mattermost_port>>/plugins/alertmanager/api/webhook?token=<<token>>
      max_alerts: 0
