apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-pv-claim
  namespace: kube-monitoring
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pv-claim
  namespace: kube-monitoring
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
