global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus/alert.rules.yaml
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
  - job_name: node-exporter
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/sa/ca.crt
    bearer_token_file: /etc/prometheus/sa/token
    kubernetes_sd_configs:
    - api_server: https://<<master_node_host>>:<<master_node_port>>
      role: pod
      tls_config:
        ca_file: /etc/prometheus/sa/ca.crt
      bearer_token_file: /etc/prometheus/sa/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        regex: node-exporter-(.+)
        action: keep
      - target_label: __address__
        replacement: <<master_node_host>>:<<master_node_port>>
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        regex: ((.+);(.+))
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-monitoring/pods/${2}:${3}/proxy/metrics

  - job_name: kube-state-metrics
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/sa/ca.crt
    bearer_token_file: /etc/prometheus/sa/token
    kubernetes_sd_configs:
    - api_server: https://<<master_node_host>>:<<master_node_port>>
      role: pod
      tls_config:
        ca_file: /etc/prometheus/sa/ca.crt
      bearer_token_file: /etc/prometheus/sa/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name]
        regex: kube-state-metrics-(.+)
        action: keep
      - target_label: __address__
        replacement: <<master_node_host>>:<<master_node_port>>
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        regex: ((.+);(.+))
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/kube-monitoring/pods/${2}:${3}/proxy/metrics

  - job_name: kubernetes-nodes-cadvisor
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/sa/ca.crt
    bearer_token_file: /etc/prometheus/sa/token
    kubernetes_sd_configs:
    - api_server: https://<<master_node_host>>:<<master_node_port>>
      role: node
      tls_config:
        ca_file: /etc/prometheus/sa/ca.crt
      bearer_token_file: /etc/prometheus/sa/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: <<master_node_host>>:<<master_node_port>>
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

  - job_name: apiserver
    scheme: https
    honor_labels: true
    kubernetes_sd_configs:
    - api_server: https://<<master_node_host>>:<<master_node_port>>
      role: endpoints
      tls_config:
        ca_file: /etc/prometheus/sa/ca.crt
      bearer_token_file: /etc/prometheus/sa/token
    tls_config:
      ca_file: /etc/prometheus/sa/ca.crt
    bearer_token_file: /etc/prometheus/sa/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "ingress-nginx"
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/sa/ca.crt
    bearer_token_file: /etc/prometheus/sa/token
    kubernetes_sd_configs:
    - api_server: https://<<master_node_host>>:<<master_node_port>>
      role: pod
      tls_config:
        ca_file: /etc/prometheus/sa/ca.crt
      bearer_token_file: /etc/prometheus/sa/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
        regex: (ingress-nginx-controller-(.+);10254)
        action: keep
      - target_label: __address__
        replacement: <<master_node_host>>:<<master_node_port>>
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/ingress-nginx/pods/${1}:10254/proxy/metrics
