apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-monitoring
  labels:
    app: prometheus
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus-server
  sessionAffinity: ClientIP
