apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.9.2
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/managed-by: intelligent_te
  name: kube-state-metrics
  namespace: kube-monitoring
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
  - name: telemetry
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
