kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: kube-monitoring
data:
  config.yml: |-
    route:
      receiver: mattermost
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: mattermost
          match:
            severity: mattermost
          group_wait: 10s
          repeat_interval: 1m
  
    receivers:
    - name: mattermost
      webhook_configs:
        - send_resolved: true
          url: http://10.10.10.130:8065/plugins/alertmanager/api/webhook?token=RJFxkGjbbb2LB2UWE7qeR77hg9reHdAK
          max_alerts: 0
